import Link from "next/link";
import "../globals.css";
import { FeatureFlagsProvider } from "@/lib/feature-flags";
import { getFeatureFlagSnapshot } from "@/lib/feature-flags/server";
import { OnboardingShell } from "./onboarding-shell";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const featureFlagSnapshot = getFeatureFlagSnapshot()

  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen m-0">
        <FeatureFlagsProvider snapshot={featureFlagSnapshot}>
          <header className="h-20 flex items-center px-6 shrink-0">
            <Link href="/" className="text-xl font-bold tracking-tight"><span className="text-zinc-500">Buy</span>Alan</Link>
          </header>
          <main className="flex-1 flex flex-col justify-center">
            <div className="max-w-xl mx-auto text-center p-6 w-full ">
              <OnboardingShell>{children}</OnboardingShell>
            </div>
          </main>
        </FeatureFlagsProvider>
      </body>
    </html>
  )
}
